# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('rescate', models.DateField()),
                ('adoptante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona')),
            ],
            options={
                'verbose_name': 'perro',
                'verbose_name_plural': 'perros',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(default='desconocida', max_length=100)),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'vacuna',
                'verbose_name_plural': 'vacunas',
            },
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canino.Raza'),
        ),
        migrations.AddField(
            model_name='perro',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canino.Sexo'),
        ),
        migrations.AddField(
            model_name='perro',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='canino.Vacuna'),
        ),
    ]
